dist: trusty

language: c

compiler: gcc

addons:
  apt:
    packages:
    - gcc-arm-linux-gnueabihf
    - libc6-dev-armhf-cross

env:
- TARGET="arm-linux-gnueabihf"
  XCC="${TARGET}-gcc"
- TARGET=$(gcc -dumpmachine) XCC="gcc"

script:
- CC=${XCC} make
