dist: trusty

language: c

compiler: gcc

addons:
  apt:
    packages:
    - gcc-arm-linux-gnueabihf

env:
- TARGET="arm-linux-gnueabihf"
  CC="${TARGET}-gcc"
- TARGET=$(gcc -dumpmachine) CC="gcc"

script:
- make
